#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gradingStudents' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY grades as parameter.
#

def gradingStudents(grades):
    # Write your code here
    integer = []
    for grade in grades:
        ceilGrade = ((grade//5)+1) * 5        
        if grade < 40:
            if 40 - grade < 3:
                integer.append("40")
            else:
                integer.append(grade)
        elif ceilGrade - grade < 3:
            integer.append(ceilGrade)
        elif ceilGrade - grade >= 3:
            integer.append(grade)
    return integer

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')
 
    grades_count = int(input().strip())

    grades = []

    for _ in range(grades_count):
        grades_item = int(input().strip())
        grades.append(grades_item)

    result = gradingStudents(grades)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
